sudo: required
services:
  - docker

before_install:
  - docker build -t mhantl/react-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true mhantl/react-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-004030006141"
  backet_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"