FROM node:alpine
USER root
WORKDIR /app
#WORKDIR /usr/src/app
#RUN export PATH=$PATH:/app/node_modules
COPY package.json .

#RUN npm install
RUN npm install -g n lts
RUN npm install -g npm@7.11.2
RUN npm audit
RUN npm install react
RUN npm install react-scripts -g
RUN npm audit
#RUN npm run test --verbose
#RUN yarn run build

#winpty docker run -it -p 3000:3000 -v /app/node_modules -v "/$(PWD)":/app mhantl/react-frontend

#COPY . .

CMD ["npm","run","start"]